spring:
  profiles:
    active: ${SPRING_PROFILE:with-mocks}
  jpa:
    hibernate:
      ddl-auto: create # TODO только для тестов
    properties:
      hibernate:
        order_by.default_null_ordering: last
        format_sql: true
        default_schema: public
    open-in-view: false
    show-sql: false
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:authservice}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  servlet:
    context-path: /auth

email-params:
  code:
    lifespan-seconds: 60
    length: 8
auth-params:
  refresh:
    lifespan-days: 7
    length: 128
  jwt:
    lifespan-seconds: 120
