services:
  email-sender:
    endpoint: ${EMAIL_SENDER_URL:http://localhost:8888}/sender/send_message

spring:
  profiles:
    active: ${SPRING_PROFILE:development}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_by.default_null_ordering: last
        format_sql: true
        default_schema: public
    open-in-view: false
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:authservice}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}  # RabbitMQ server host
    port: ${RABBITMQ_PORT:5672}       # RabbitMQ server port
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}

  main:
    web-application-type: servlet

server:
  servlet:
    context-path: /auth
  port: 8080

email-params:
  code:
    lifespan-seconds: ${EMAIL_CODE_LIFESPAN:60}
    length: ${EMAIL_CODE_LENGTH:8}
auth-params:
  refresh:
    lifespan-days: ${REFRESH_LIFESPAN:7}
    length: ${REFRESH_LENGTH:128}
  jwt:
    lifespan-seconds: ${JWT_LIFESPAN:120}

management:
  endpoint:
    health:
      probes:
        enabled: true

